#ModTRS configuration!
modtrs:
  
  #Words that a user is not allowed to say in a mod request (e.g. ['flymod', 'you suck', 'etc'])
  blacklist: []
    
  #Notify mods when someone makes a new request
  notify_mods: true
    
  #Whenever someone runs a ModTRS command, log it in the console
  log_commands: true
    
  #How many requests a user is allowed to have open at one time
  max_requests: 5
    
  #How many requests should show up per page on /check
  requests_per_page: 5
  
  #For development only, no need for users to use this
  debug: false